### ISSUE TITLE
Does this script update IPv6  ? 

### ISSUE THREAD

**Issue by pcecilio** [pv8/noipy#45]
Does this script update IPv6  ?

**Comment by pv8** [comment]
If you're using a custom DDNS (using `--generic` flag) and it supports IPv6, then **YES**.

For the supported providers:

Provider name | support IPv6? | `noipy` ready? 
------------ | ------------- | -------------
[No-IP](https://www.noip.com/) | NO | depends on provider support
[DynDNS](https://www.dyn.com/) | YES | YES
[DuckDNS](https://www.duckdns.org/) | YES | Coming soon...
